### ISSUE TITLE
Ducky script converter?

### ISSUE THREAD

**Issue by ghost** [TomBrlek/PicoUSB#1]
Good day.

I just received my picousb and I'm loving it.

My only "con" with it that it doesn't use the standard ducky script used on the internet. There are a lot of cool scripts out there made by ppl like Jacoby but can't use it as is.

Are there are any resources out there to help convert the standard ducky script to the picousb script?

**Comment by TomBrlek** [comment]
Hello,

I do not have a script yet. Maybe it would be better that PicoUSB ran ducky
scripts out of the box. Maybe that should be next on the roadmap.

Let me make it work in the following days.

Ping me before the end of the week in case I forget.

Kind regards,

Tomislav
voltmake.com

**Comment by ghost** [comment]
Will do. Thank you 👍

**Comment by reppad** [comment]
There may be some interesting things about this topic here: https://github.com/dbisu/pico-ducky

**Comment by TomBrlek** [comment]
Will do, thanks!

This was one of the reasons I made the PicoUSB. Maybe I should get in
contact with them. Thanks!

Tomislav Brlek, mag. ing. el.
Programiranje in Storitve, Tomislav Brlek SP,
Ul. škofa Maksimilijana Držečnika 7
2000 Maribor | Slovenia
+386 31 016 296

**Comment by tbrlek** [comment]
You can use the Pico Ducky in order to use Ducky Script on the PicoUSB. I have been in contact with the creator of Pico Ducky and they gave the green light.

Only thing you might want to change is the:
LED output pin to GPIO 12
Button input pin to GPIO 25

**Comment by reppad** [comment]
It works well, I confirm.

Regarding the pin for the LED, it is set to GP24 in the PicoUSB software.
I made a small PR https://github.com/TomBrlek/PicoUSB/pull/2 about it, I don't know if you have seen it?

**Comment by TomBrlek** [comment]
Thanks! Have not seen it. 

Also, now I made it so LED always turns on when code is being executed.
