### ISSUE TITLE
Where can I find a mac keyboard layout?

### ISSUE THREAD

**Issue by r1979** [TomBrlek/PicoUSB#3]
See title.

**Comment by TomBrlek** [comment]
You can find the detailed explanations of the keys you can use in /lib/adafruit_hid/keycode.py (https://github.com/TomBrlek/PicoUSB/blob/main/lib/adafruit_hid/keycode.py)

For example:

    GUI = LEFT_GUI
    """Alias for LEFT_GUI; GUI is also known as the Windows key, Command (Mac), or Meta"""

PicoUSB (this will press windows key or mac command key regardless if you use windows or mac):

press(GUI)
