### ISSUE TITLE
Loop mode

### ISSUE THREAD

**Issue by raimondi1337** [TomBrlek/PicoUSB#4]
It's unclear from the readme if there's a way to loop pico_usb.txt

Is there a GOTO statement or a REPEAT function I can set? I would like my script to run repeatedly forever.

**Comment by TomBrlek** [comment]
Pushed a new update. I have added a "loop" command. It forever loops everything after the loop command. (Use loop only once.)

Example:
delay(1)
press(windows)
delay(1)
write(Hello from PicoUSB!)
loop()
write(!)

Will write: Hello from PicoUSB!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!... (forever)

**Comment by TomBrlek** [comment]
Pushed a new update. I have added a "loop" command. It forever loops everything after the loop command. (Use loop only once.)

Example:
delay(1)
press(windows)
delay(1)
write(Hello from PicoUSB!)
loop()
write(!)

Will write: Hello from PicoUSB!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!... (forever)

**Comment by raimondi1337** [comment]
Wow that was fast, I was halfway through implementing this so that I could send you a PR, including the small refactor of the line execution code, thanks man!

**Comment by Andynam0** [comment]
I thought something was wrong! This is an annoying "first" payload, I'd leave off the last 4 lines off or commented out in the MAIN branch.
loop() \n write(!) \n move(5, 5) \n delay(0.5)

My mouse was moving and it seems to make my SHIFT key "stick" even after unplugging it. 
![image](https://github.com/user-attachments/assets/c819b4b2-f34e-4c66-9735-290852909496)
